[package]
name = "OFSExtractor"
authors = ["TheGreatMcPain"]
version = "1.2.0"
edition = "2024"
license = "MIT"

[dependencies]
exitcode = "1.1.2"
h264-reader = "0.8.0"
itertools = "0.14.0"
memchr = "2.8.0"
memmap3 = "0.1.0"
memmem = "0.1.1"
rand = "0.10.0"
shellexpand = "3.1.1"
simpleargs = { git = "https://github.com/TheGreatMcPain/simpleargs.git" }
wincode = { version = "0.4.5", features = ["derive"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
